### ISSUE TITLE
Some parser notes

### ISSUE THREAD

**Issue by ptmcg** [maxfischer2781/compyle#1]
Not an issue so much as some review notes - free advice, so worth what you paid for it. Follow, contest, ignore, as you wish.

Some parser notes:

Your decorator for your parse actions took me a little getting used to, but I'm getting the hang of it.

I didn't see any calls to `pp.ParserElement.enablePackrat()`. Packrat parsing is usually a big win for recursive expression parsers. Think of it as parse-time memoizing.

Your decorator for decimal:

    @rule(pp.Combine(pp.Word(pp.nums) + "." - pp.Word(pp.nums).setName('integer')))

is probably better written:

    @rule(pp.Combine(pp.Regex(r"\d+\.\d+"))

I used to use `Combine` to build up real number expressions, but they are a big parse-time penalty compared to using a `Regex`, and the regexen don't bleed out into the larger program and make a big mess. (No leading '-' allowed?) There are also a number of numeric expressions defined in `pp.pyparsing_common`, including auto-conversion to their respective types. Or just use `pp.pyparsing_common.number`, and it will match floats, ints, and scientific notation and give back a value of the correct type (or use `pp.pyparsing_common.fnumber` and always get a float).

Repeated use of `pp.Word(pp.nums)` instead of defining and reusing a single expression will de-optimize packratting.

Generally good use of '-' error stop operator, except I don't think you want the first one in the decorator for `assignment`.

`pp.MatchFirst(list("+-*/"))` can also be written as `pp.oneOf("+ - * /")`. `oneOf` is especially nice in that it will rearrange given symbols if it detects a clash. Compare `MatchFirst("< > = <= >= !=".split())` with `oneOf(""< > = <= >= !=")`. `oneOf` will correctly test '>=' ahead of '>', `MatchFirst` won't.

Since your language is inherently line-oriented, can you choose to drop newlines from the default whitespace set? `ParserElement.setDefaultWhitespaceChars(" \t")` would do it.

In `LINE_COMMENT`:

    LINE_COMMENT = pp.Suppress(pp.Optional(pp.Literal("#") + pp.SkipTo(pp.StringEnd())))

can be written:

    LINE_COMMENT = pp.Suppress(pp.Optional("#" + pp.restOfLine))

I haven't tried it, but you can also replace `SkipTo` in places with `...`:

    LINE_COMMENT = pp.Suppress(pp.Optional(pp.Literal("#") + ... + pp.StringEnd()))

You might also want to use `LineEnd` instead of `StringEnd`, in the even you start parsing multiline statements someday.

All I've got so far.

**Comment by maxfischer2781** [comment]
Nice, thanks for these suggestions! I've added most of these now; kept the - in ``assignment``, since it only ever gets evaluated alongside the ``evaluation`` statement. By the way, ``... + pp.LineEnd()`` does indeed work well!
